# version: '3.8'  # Removed obsolete version attribute

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Ollama runs natively on Windows - no Docker container needed
  # TigerGraph Community Edition runs separately via scripts

volumes:
  redis_data:

networks:
  default:
    name: hybrid_network 